### ISSUE TITLE
Quick extension enable/disable

### ISSUE THREAD

**Issue by hisbvdis** [DNishanth/Noncontiguous-Text-Selection#1]
Thanks for great and useful extension. 

It seems that it would be more convenient to be able to quickly enable / disable this extension, since there is no need for it constantly and to avoid problems with highlighting in interactive input fields. For example, by clicking on button in extension dropdown menu.

**Comment by DNishanth** [comment]
Thanks for bringing up this issue, it's definitely a valid point. I will add a button or some other way to quickly toggle the extension.

**Comment by hisbvdis** [comment]
> Thanks for bringing up this issue, it's definitely a valid point. I will add a button or some other way to quickly toggle the extension.

This is very good news. Thanks.
